### ISSUE TITLE
Invalid argument(s): "positions" and "colors" lengths must match.

### ISSUE THREAD

**Issue by Kassan424kh** [arnovanliere/object_3d#1]
```
======== Exception caught by rendering library =====================================================
The following ArgumentError was thrown during paint():
Invalid argument(s): "positions" and "colors" lengths must match.

The relevant error-causing widget was: 
  CustomPaint CustomPaint:file:///Users/khalilkhalil/.pub-cache/hosted/pub.dev/object_3d-0.0.1/lib/object_3d.dart:104:14
When the exception was thrown, this was the stack: 
#0      new Vertices (dart:ui/painting.dart:4762:7)
#1      _ObjectPainter.paint (package:object_3d/object_3d.dart:257:15)
#2      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:588:13)
#3      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:630:7)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#9      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#12     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2882:15)
#13     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:640:5)
#14     RenderStack.paint (package:flutter/src/rendering/stack.dart:656:7)
#15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#17     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2882:15)
#18     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#21     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#22     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:662:11)
#23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#25     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#26     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2043:15)
#27     PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:575:14)
#28     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2030:21)
#29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#31     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:250:13)
#34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3208:7)
#36     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:166:11)
#37     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:109:5)
#38     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1156:31)
#39     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1166:15)
#40     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:593:23)
#41     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#42     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#43     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#44     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#45     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#46     _invoke (dart:ui/hooks.dart:312:13)
#47     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#48     _drawFrame (dart:ui/hooks.dart:283:31)
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#8b7a8
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, h=891.4)
...  size: Size(411.4, 891.4)
...  painter: _ObjectPainter#61313()
...  preferredSize: Size(400.0, 400.0)
RenderObject: RenderCustomPaint#8b7a8
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, h=891.4)
  size: Size(411.4, 891.4)
  painter: _ObjectPainter#61313()
  preferredSize: Size(400.0, 400.0)
====================================================================================================
```

**Comment by arnovanliere** [comment]
Probably an invalid .obj file. This happens if you have faces with less or more than 3 vertices.

**Comment by Kassan424kh** [comment]
Ahh ok, i fixed the problem thank you
